line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

disabled_rules:
  - trailing_comma
  - identifier_name

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing

excluded:
  - .build
  - build
